runtime: nodejs18
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 5

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  NODE_ENV: 'production'
