steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-myuzo-sounds-repo/frontend', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-myuzo-sounds-repo/frontend']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce-myuzo-sounds-repo/frontend'
