import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Hero Section */}
        <div className="bg-blue-500 text-white text-center p-12">
          <h1 className="text-4xl font-bold">Welcome to Our Service</h1>
          <p className="text-xl mt-4">Explore the amazing world of our product.</p>
          <div className="mt-8">
            <a href="#" className="bg-white text-blue-500 px-6 py-3 rounded shadow">Learn More</a>
            <a href="#" className="ml-4 border border-white px-6 py-3 rounded shadow">Sign Up</a>
          </div>
        </div>

        {/* Feature Section */}
        <div className="container mx-auto px-6 py-12">
          <div className="grid md:grid-cols-3 gap-6">
            {/* Feature 1 */}
            <div className="bg-white rounded shadow p-6">
              <div className="text-center mb-4">
                {/* Icon or Image */}
              </div>
              <h3 className="font-bold text-lg">Feature One</h3>
              <p className="text-gray-600 mt-2">Description of the first feature.</p>
            </div>
            {/* Feature 2 */}
            <div className="bg-white rounded shadow p-6">
              <div className="text-center mb-4">
                {/* Icon or Image */}
              </div>
              <h3 className="font-bold text-lg">Feature Two</h3>
              <p className="text-gray-600 mt-2">Description of the second feature.</p>
            </div>
            {/* Feature 3 */}
            <div className="bg-white rounded shadow p-6">
              <div className="text-center mb-4">
                {/* Icon or Image */}
              </div>
              <h3 className="font-bold text-lg">Feature Three</h3>
              <p className="text-gray-600 mt-2">Description of the third feature.</p>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
